const test=require('node:test'),assert=require('node:assert/strict'),C=require('../src/catalogue.js'),E=require('../src/engine.js');
function game(n=5){const g=E.createGame(Array.from({length:n},(_,i)=>({id:`p${i+1}`,name:`Player ${i+1}`})),{...C.defaults,parity:false});g.players.forEach((p,i)=>p.team=i===n-1?'parasites':'force');g.phase='operations';g.round=1;return g;}
function run(g,id,targets=[],result='',overrideTargets=null){g.cursor=0;g.turns=[{player:'p1',operation:id,override:result||overrideTargets?{result,targets:overrideTargets||[]}:null,targets:null,done:false}];return E.runOperation(g,{targets});}
test('Majority Report works with three players by including its owner',()=>{const g=game(3);assert.equal(run(g,'majority',['p1','p2','p3']).team,'force');g.players[0].special='source';assert.equal(run(g,'majority',['p1','p2','p3']).team,'parasites');});
test('Chain compares apparent allegiances and Counterintelligence sees actual teams',()=>{const g=game();g.players[1].special='suspicious';assert.equal(run(g,'chain',['p2']).same,false);g.players[0].special='counterintel';assert.equal(run(g,'chain',['p2']).same,true);});
test('Threat compares targets to the owner’s actual team and Source flips the combined answer',()=>{const g=game();g.players[0].special='suspicious';assert.equal(run(g,'threat',['p2','p5']).opposing,true);g.players[0].special='source';assert.equal(run(g,'threat',['p2','p5']).opposing,false);});
test('Cross-Reference returns two different targets, excludes owner, and preserves manual second target',()=>{const g=game();const r=run(g,'cross',['p2']);assert.equal(r.targets.length,2);assert.equal(r.targets[0],'p2');assert(!r.targets.includes('p1'));assert.equal(new Set(r.targets).size,2);assert.deepEqual(run(g,'cross',[],'same',['p2','p5']).targets,['p2','p5']);});
test('Audit counts active apparent allegiances, bypasses disguises, and complements under Source',()=>{const g=game();g.players[1].special='suspicious';g.players[4].special='cover';assert.equal(run(g,'audit').count,1);g.players[0].special='counterintel';assert.equal(run(g,'audit').count,1);g.players[1].special=null;assert.equal(run(g,'audit').count,1);g.players[0].special='source';assert.equal(run(g,'audit').count,5);assert.equal(run(g,'audit',[],'0').count,0);assert.throws(()=>run(g,'audit',[],'6'),/cannot exceed/);});
test('Background Check detects existence but never reveals the role ID',()=>{const g=game();g.players[1].special='fixed';const r=run(g,'background',['p2']);assert.equal(r.answer,true);assert(!JSON.stringify(r).includes('fixed'));g.players[0].special='source';assert.equal(run(g,'background',['p2']).answer,false);});
test('Divided Loyalties detects agendas and secured wins but not ordinary team membership',()=>{const g=game();assert.equal(run(g,'loyalties',['p2']).answer,false);g.players[1].agenda={id:'grudge',target:'p5'};assert.equal(run(g,'loyalties',['p2']).answer,true);g.players[1].agenda=null;g.players[1].secured=[{id:'grudge',round:1}];assert.equal(run(g,'loyalties',['p2']).answer,true);});
function truths(r,p){return r.statements.map(s=>({'They are Force.':p.team==='force','They are a Parasite.':p.team==='parasites','They have a hidden special role.':!!p.special,'They have no hidden special role.':!p.special,'They have a personal victory condition or secured personal win.':!!p.agenda||!!p.secured.length,'They follow their team’s usual victory condition.':!p.agenda&&!p.secured.length}[s]));}
test('Personnel has exactly one true statement, while Source receives two false statements',()=>{const g=game();g.players[1].special='fixed';for(let i=0;i<30;i++)assert.equal(truths(run(g,'personnel',['p2']),g.players[1]).filter(Boolean).length,1);g.players[0].special='source';for(let i=0;i<30;i++)assert.deepEqual(truths(run(g,'personnel',['p2']),g.players[1]),[false,false]);assert.deepEqual(truths(run(g,'personnel',['p2'],'true'),g.players[1]),[true,true]);});
test('Every new operation works in both game modes and retains private results',()=>{for(const singleRound of [true,false])for(const id of ['majority','chain','threat','cross','audit','background','loyalties','personnel']){const g=game(3);g.config.singleRound=singleRound;const op=C.operations.find(o=>o.id===id);const targets=g.players.filter(p=>op.allowSelf||p.id!=='p1').slice(0,op.targets).map(p=>p.id);assert(run(g,id,targets));}});
