const test=require('node:test'),assert=require('node:assert/strict'),C=require('../src/catalogue.js'),E=require('../src/engine.js');
function game(parasites=['p4','p5']){const g=E.createGame([1,2,3,4,5].map(n=>({id:`p${n}`,name:`Player ${n}`})),{...C.defaults,singleRound:true,parity:true});g.players.forEach(p=>p.team=parasites.includes(p.id)?'parasites':'force');g.round=1;g.phase='discussion';return g;}
function vote(g,target){E.startVoting(g);while(g.phase==='voting'){const voter=g.voters[g.cursor];E.vote(g,voter===target?'p1':target);}return g;}
test('One-round option defaults off and survives config serialization',()=>{assert.equal(E.cleanConfig({}).singleRound,false);assert.equal(E.cleanConfig(JSON.parse(JSON.stringify({singleRound:true}))).singleRound,true);});
test('Jailing one Parasite awards Force victory even when another remains',()=>{const g=vote(game(),'p5');assert.equal(g.winner,'force');assert.equal(E.active(g).filter(p=>p.team==='parasites').length,1);assert.throws(()=>E.startRound(g),/already ended/);});
test('Jailing Force awards Parasite victory regardless of normal parity',()=>{const g=vote(game(['p5']),'p2');assert.equal(g.winner,'parasites');assert.equal(g.tally.reveal,'force');});
test('Actual allegiance, not a disguise, determines one-round victory',()=>{const g=game();g.players[4].special='cover';vote(g,'p5');assert.equal(g.winner,'force');});
test('A tied vote ends in a draw and Infatuation shares that draw',()=>{const g=game();g.players[0].agenda={id:'infatuation',target:'p2'};E.startVoting(g);for(const target of ['p2','p3','p4','p5','p1'])E.vote(g,target);assert.equal(g.winner,'draw');assert(E.outcomes(g).every(p=>p.draw));assert.throws(()=>E.startRound(g),/already ended/);});
test('Personal victories still apply after the one-round team decision',()=>{const g=game();g.players[4].agenda={id:'scapegoat',target:null};vote(g,'p5');assert.equal(g.winner,'force');assert(E.outcomes(g).find(p=>p.id==='p5').win);});
test('One-round mode waits for voting at parity or with no Parasites',()=>{const g=game(['p1','p2','p3']);assert.equal(E.teamWinner(g),null);g.players.forEach(p=>p.team='force');assert.equal(E.teamWinner(g),null);g.players[2].jailed=true;g.players[3].jailed=true;g.players[4].jailed=true;assert.equal(E.teamWinner(g).team,'force');});
